// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2gVkJd1WlI9HR2uq9c9b9b77Ci7SVMs',
    appId: '1:1022908317554:web:756bc9f06a0d21ea5767eb',
    messagingSenderId: '1022908317554',
    projectId: 'chatingapp-c67a0',
    authDomain: 'chatingapp-c67a0.firebaseapp.com',
    storageBucket: 'chatingapp-c67a0.firebasestorage.app',
    measurementId: 'G-E1TVJXFTZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28ZqUxuyoWi6S1-Vzt8pqyDTpxxggc4U',
    appId: '1:1022908317554:android:8ef07b08783ee2fd5767eb',
    messagingSenderId: '1022908317554',
    projectId: 'chatingapp-c67a0',
    storageBucket: 'chatingapp-c67a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0DNyIxQYX26U27FZGIssqE1dEUBbfYm0',
    appId: '1:1022908317554:ios:e873ce8766e7cfd35767eb',
    messagingSenderId: '1022908317554',
    projectId: 'chatingapp-c67a0',
    storageBucket: 'chatingapp-c67a0.firebasestorage.app',
    androidClientId: '1022908317554-l9tt5bil4io0jal3gpsq0cpa3ingq83l.apps.googleusercontent.com',
    iosClientId: '1022908317554-m9bj0igekh98p7llfeuial4kd7lkqgo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0DNyIxQYX26U27FZGIssqE1dEUBbfYm0',
    appId: '1:1022908317554:ios:e873ce8766e7cfd35767eb',
    messagingSenderId: '1022908317554',
    projectId: 'chatingapp-c67a0',
    storageBucket: 'chatingapp-c67a0.firebasestorage.app',
    androidClientId: '1022908317554-l9tt5bil4io0jal3gpsq0cpa3ingq83l.apps.googleusercontent.com',
    iosClientId: '1022908317554-m9bj0igekh98p7llfeuial4kd7lkqgo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg2gVkJd1WlI9HR2uq9c9b9b77Ci7SVMs',
    appId: '1:1022908317554:web:dcbc171e1be48ba45767eb',
    messagingSenderId: '1022908317554',
    projectId: 'chatingapp-c67a0',
    authDomain: 'chatingapp-c67a0.firebaseapp.com',
    storageBucket: 'chatingapp-c67a0.firebasestorage.app',
    measurementId: 'G-9T06MXWD38',
  );
}
